// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Robert J. Lee
//
// Writes docs/gatelink/gatelink-config.md from /lib/lran-config/'s table to stdout. Task
// L4; GateLink Impl Plan 6.4 and Protocol Library Plan 4 ask for the document to be
// derived from the table by code (D44).
//
// IT INCLUDES table.h ITSELF, so the document is an output of the header rather than a
// description of it. tools/checks/config_doc.py builds this, diffs what it prints against
// the committed file, and fails when they differ.

#include <cstdio>

#include "lran/config.h"
#include "lran/config/table.h"
#include "lran/schema/node_config_v1.h"

using lran::PType;
using lran::config::Access;
using lran::config::Owner;
using lran::config::ParamDef;

namespace {

const char* type_name(PType t) {
  switch (t) {
    case PType::U8: return "u8";
    case PType::U16: return "u16";
    case PType::U32: return "u32";
    case PType::I16: return "i16";
    case PType::I32: return "i32";
    case PType::Bool: return "bool";
  }
  return "?";
}

// D56 - a PHY row is set only through spec 12.4's commit-and-revert, from the bridge's
// topic, so the document says so rather than offering it as an ordinary setting.
const char* access_name(Access a) {
  switch (a) {
    case Access::ReadWrite: return "read-write";
    case Access::ReadOnly: return "read-only";
    case Access::Phy: return "PHY group, spec 12.4";
  }
  return "?";
}

void rows(const ParamDef* p, size_t n) {
  std::printf("| ID | Name | Type | Unit | Default | Range | Access | Meaning |\n");
  std::printf("|---|---|---|---|---|---|---|---|\n");
  for (size_t i = 0; i < n; ++i) {
    const ParamDef& d = p[i];
    std::printf("| `0x%04X` | `%s` | %s | %s | %ld | %ld to %ld | %s | %s |\n", d.id, d.name,
                type_name(d.type), d.unit != nullptr ? d.unit : "", static_cast<long>(d.def),
                static_cast<long>(d.min), static_cast<long>(d.max), access_name(d.access),
                d.doc);
  }
}

}  // namespace

int main() {
  using namespace lran::config;
  const size_t own    = readback_bytes(kGateLinkParams, kGateLinkParamCount);
  const size_t common = readback_bytes(kNodeCommonParams, kNodeCommonParamCount);

  std::printf(
      "# GateLink configuration parameters\n"
      "\n"
      "<!-- GENERATED by tools/config/dump_config_doc.cpp from "
      "lib/lran-config/include/lran/config/table.h.\n"
      "     Do not edit. Regenerate with: python3 tools/checks/config_doc.py --write -->\n"
      "\n"
      "**Every parameter GateLink holds, as `lib/lran-config/` declares it.** The table "
      "header is the\n"
      "source (D44). This file, the firmware's defaults and the Home Assistant controls "
      "are all\n"
      "derived from it, and `tools/checks/config_doc.py` fails CI when this file stops "
      "matching.\n"
      "\n"
      "**A name is permanent once Home Assistant has published it**, because it is the "
      "entity's\n"
      "`object_id` (Protocol Spec §16.7). Set a parameter on `lran/gatelink/config/set` "
      "(§16.7.2).\n"
      "A value outside its range is clamped, and the clamp is reported (§7.4).\n"
      "\n"
      "**The ranges are proposals, not measurements.** Each default comes from the GateLink "
      "PRD or\n"
      "Implementation Plan §4.4, as the row's meaning cites.\n"
      "\n"
      "## GateLink's own block, `0x1000`–`0x1FFF`\n"
      "\n");
  rows(kGateLinkParams, kGateLinkParamCount);
  std::printf(
      "\n"
      "## Every node's block, `0x0100`–`0x01FF`\n"
      "\n"
      "GateLink holds these as every node does. The PHY rows change only as a fleet "
      "operation from\n"
      "the bridge's topic (spec §12.4, D56, D59).\n"
      "\n");
  rows(kNodeCommonParams, kNodeCommonParamCount);

  // D47 - set on GateLink's topic, applied by the bridge, and never sent to the node.
  ParamDef per_node[kMaxTableParams] = {};
  size_t   n                         = 0;
  for (size_t i = 0; i < kBridgeParamCount; ++i) {
    if (kBridgeParams[i].owner == Owner::BridgePerNode) per_node[n++] = kBridgeParams[i];
  }
  std::printf(
      "\n"
      "## Held by the bridge for GateLink\n"
      "\n"
      "These are set on GateLink's topic too, but the bridge applies them and never sends "
      "them to\n"
      "the node (D47). They are not part of the node's readback.\n"
      "\n");
  rows(per_node, n);
  const size_t budget = lran::kMaxSchemaPayload - lran::schema::kConfigAckHdrLen;
  const size_t total  = own + common;
  std::printf(
      "\n"
      "## What a full readback costs\n"
      "\n"
      "A `CONFIG_ACK` has %u bytes for results (spec §7.4). GateLink's block takes %u and "
      "every\n"
      "node's block %u, so a full readback takes %u bytes.%s\n",
      static_cast<unsigned>(budget), static_cast<unsigned>(own), static_cast<unsigned>(common),
      static_cast<unsigned>(total),
      total > budget ? " It arrives as more than one message, marked\n`MORE_FOLLOWS` "
                       "(spec §7.4.1)."
                     : " It fits one message.");
  return 0;
}
