#!/usr/bin/env python3
"""Emit the W4 vectors as a C++ header of flash-resident constants.

Purely mechanical: it reads the JSON that generate.py produced and re-expresses it
as C++ initializers. It knows nothing about the protocol and derives nothing - the
JSON stays the single source of truth, and check.py remains the thing that validates
it. This only changes the transport into the test binary.

Why it exists: the target has no filesystem, and the JSON reader's fixed arena cost
945 KB of RAM against the Heltec V3's 320 KB. As `const` data these vectors live in
flash (68 KB against 8 MB) and cost essentially no RAM. Native and target then run
byte-identical data, which is the point.

    python3 tools/vectors/embed.py
"""

import json
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
OUT = HERE.parent.parent / "lib/lran-protocol/test/test_vectors/vectors_data.h"


def blob(name, hexstr):
    """A byte array. Zero-length arrays are illegal in C++, so emit a 1-byte dummy
    and let the length field say 0 - `payload: ""` is a real case (PING with n=0)."""
    data = bytes.fromhex(hexstr)
    if not data:
        return f"inline constexpr uint8_t {name}[1] = {{0}};  // length 0\n", 0
    rows = []
    for i in range(0, len(data), 12):
        rows.append("    " + " ".join(f"0x{b:02x}," for b in data[i:i + 12]))
    return (f"inline constexpr uint8_t {name}[{len(data)}] = {{\n"
            + "\n".join(rows) + "\n};\n"), len(data)


def key_node(v):
    """'node:0x01' -> 1;  null -> -1."""
    k = v.get("key")
    if k is None:
        return -1
    return int(k.split(":")[1], 16)


def hdr_init(h):
    return (f'{{{h["ver"]}, "{h["type"]}", {h["src"]}, {h["dst"]}, {h["seq"]}u, '
            f'{h["ctx_id"]}u, {int(h["frag"], 16)}, {int(h["schema"], 16)}, '
            f'{int(h["hdr_flags"], 16)}}}')


def cstr(s):
    return "nullptr" if s is None else '"' + s.replace('"', '\\"') + '"'


def main():
    groups = {g: json.loads((HERE / f"vectors_{g}.json").read_text())
              for g in ("kdf", "single", "frag", "negative")}

    out = ['// SPDX-License-Identifier: MIT',
           '// Copyright (c) 2026 Robert J. Lee',
           '//',
           '// GENERATED by tools/vectors/embed.py from tools/vectors/vectors_*.json.',
           '// DO NOT EDIT. Regenerate after any change to the vectors (spec 13.2).',
           '//',
           '// Flash-resident so the suite runs on target, which has no filesystem and',
           '// 320 KB of RAM. Native and target consume the same bytes.',
           '',
           '#pragma once',
           '',
           '#include <cstddef>',
           '#include <cstdint>',
           '',
           'namespace lran_vectors {',
           '',
           '// A vector\'s declared header. `type` is the spec 6 NAME, not the numeric',
           '// value: the name-to-value mapping is itself part of what is witnessed.',
           'struct HdrSpec {',
           '  uint8_t     ver;',
           '  const char* type;',
           '  uint8_t     src;',
           '  uint8_t     dst;',
           '  uint16_t    seq;',
           '  uint32_t    ctx_id;',
           '  uint8_t     frag;',
           '  uint8_t     schema;',
           '  uint8_t     hdr_flags;',
           '};',
           '',
           'struct KdfVec {',
           '  const char*    name;',
           '  uint8_t        node_id;',
           '  const uint8_t* master;   uint16_t master_len;',
           '  const uint8_t* info;     uint16_t info_len;',
           '  const uint8_t* salt;     uint16_t salt_len;',
           '  const uint8_t* node_key; uint16_t node_key_len;',
           '};',
           '',
           'struct SingleVec {',
           '  const char*    name;',
           '  bool           decode_only;   // spec 5.8 - no conforming encoder emits it',
           '  HdrSpec        hdr;',
           '  const uint8_t* payload;  uint16_t payload_len;',
           '  int16_t        key_node;      // -1 = frame carries no MAC',
           '  const uint8_t* frame;    uint16_t frame_len;',
           '  uint16_t       declared_len;  // the vector\'s own frame_len field',
           '  uint8_t        self;',
           '  uint32_t       expect_ctx;',
           '  const char*    status;',
           '  const uint8_t* dec_payload; uint16_t dec_payload_len;',
           '  bool           mac_present;',
           '};',
           '',
           'struct FragVec {',
           '  const char*           name;',
           '  HdrSpec               hdr;',
           '  const uint8_t*        payload; uint16_t payload_len;',
           '  uint16_t              frag_chunk;',
           '  int16_t               key_node;',
           '  const uint8_t* const* frames;',
           '  const uint16_t*       frame_lens;',
           '  uint8_t               total;',
           '  const uint16_t*       fragment_lens;',
           '  const uint8_t*        order; uint8_t order_len;',
           '  uint8_t               self;',
           '  uint32_t              expect_ctx;',
           '  const uint8_t*        reassembled; uint16_t reassembled_len;',
           '  const char*           counter;   // nullptr when the vector names none',
           '  // spec 11.2 - a single-frame frame delivered after `inter_after`',
           '  // entries of `order`. nullptr when the vector interposes nothing.',
           '  const uint8_t*        inter_frame; uint16_t inter_frame_len;',
           '  const uint8_t*        inter_payload; uint16_t inter_payload_len;',
           '  uint8_t               inter_after;',
           '};',
           '',
           'struct NegVec {',
           '  const char*    name;',
           '  const uint8_t* frame; uint16_t frame_len;',
           '  uint8_t        self;',
           '  uint32_t       expect_ctx;',
           '  const char*    status;',
           '  const char*    counter;',
           '  int16_t        key_node;',
           '};',
           '']

    # ---- kdf -------------------------------------------------------------
    rows = []
    for i, v in enumerate(groups["kdf"]["vectors"]):
        for f in ("master_key", "info", "salt", "node_key"):
            src, n = blob(f"k{i}_{f}", v[f])
            out.append(src)
            v[f + "_n"] = n
        rows.append(f'    {{{cstr(v["name"])}, {int(v["node_id"], 16)}, '
                    f'k{i}_master_key, {v["master_key_n"]}, k{i}_info, {v["info_n"]}, '
                    f'k{i}_salt, {v["salt_n"]}, k{i}_node_key, {v["node_key_n"]}}},')
    out.append("inline constexpr KdfVec kKdf[] = {\n" + "\n".join(rows) + "\n};\n")

    # ---- single ----------------------------------------------------------
    rows = []
    for i, v in enumerate(groups["single"]["vectors"]):
        ps, pn = blob(f"s{i}_payload", v["payload"]);       out.append(ps)
        fs, fn = blob(f"s{i}_frame", v["frame"]);           out.append(fs)
        dec = v["decode"]
        ds, dn = blob(f"s{i}_dec", dec.get("payload", "")); out.append(ds)
        rows.append(
            f'    {{{cstr(v["name"])}, {str(v.get("decode_only", False)).lower()}, '
            f'{hdr_init(v["header"])}, s{i}_payload, {pn}, {key_node(v)}, '
            f's{i}_frame, {fn}, {v["frame_len"]}, {dec["self"]}, '
            f'{dec["expect_ctx_id"]}u, {cstr(dec["status"])}, s{i}_dec, {dn}, '
            f'{str(dec.get("mac_present", False)).lower()}}},')
    out.append("inline constexpr SingleVec kSingle[] = {\n" + "\n".join(rows) + "\n};\n")

    # ---- frag ------------------------------------------------------------
    rows = []
    for i, v in enumerate(groups["frag"]["vectors"]):
        ps, pn = blob(f"f{i}_payload", v["payload"]); out.append(ps)
        names, lens = [], []
        for j, fr in enumerate(v["frames"]):
            fs, fl = blob(f"f{i}_fr{j}", fr); out.append(fs)
            names.append(f"f{i}_fr{j}"); lens.append(fl)
        out.append(f'inline constexpr const uint8_t* const f{i}_frames[] = {{'
                   + ", ".join(names) + "};\n")
        out.append(f'inline constexpr uint16_t f{i}_frame_lens[] = {{'
                   + ", ".join(str(x) for x in lens) + "};\n")
        out.append(f'inline constexpr uint16_t f{i}_frag_lens[] = {{'
                   + ", ".join(str(x) for x in v["fragment_lens"]) + "};\n")
        dec = v["decode"]
        out.append(f'inline constexpr uint8_t f{i}_order[] = {{'
                   + ", ".join(str(x) for x in dec["delivery_order"]) + "};\n")
        rs, rn = blob(f"f{i}_reasm", dec["reassembled"]); out.append(rs)
        ip = v.get("interpose")
        if ip is None:
            inter = "nullptr, 0, nullptr, 0, 0"
        else:
            ifs, ifn = blob(f"f{i}_inter", ip["frame"]);        out.append(ifs)
            ips, ipn = blob(f"f{i}_inter_pl", ip["payload"]);   out.append(ips)
            inter = (f'f{i}_inter, {ifn}, f{i}_inter_pl, {ipn}, {ip["after"]}')
        rows.append(
            f'    {{{cstr(v["name"])}, {hdr_init(v["header"])}, f{i}_payload, {pn}, '
            f'{v["frag_chunk"]}, {key_node(v)}, f{i}_frames, f{i}_frame_lens, '
            f'{len(v["frames"])}, f{i}_frag_lens, f{i}_order, '
            f'{len(dec["delivery_order"])}, {dec["self"]}, {dec["expect_ctx_id"]}u, '
            f'f{i}_reasm, {rn}, {cstr(dec.get("counter"))}, {inter}}},')
    out.append("inline constexpr FragVec kFrag[] = {\n" + "\n".join(rows) + "\n};\n")

    # ---- negative --------------------------------------------------------
    rows = []
    for i, v in enumerate(groups["negative"]["vectors"]):
        fs, fn = blob(f"n{i}_frame", v["frame"]); out.append(fs)
        dec = v["decode"]
        rows.append(
            f'    {{{cstr(v["name"])}, n{i}_frame, {fn}, {dec["self"]}, '
            f'{dec["expect_ctx_id"]}u, {cstr(dec["status"])}, '
            f'{cstr(dec.get("counter"))}, {key_node(v)}}},')
    out.append("inline constexpr NegVec kNegative[] = {\n" + "\n".join(rows) + "\n};\n")

    out.append("inline constexpr size_t kKdfCount      = sizeof(kKdf) / sizeof(kKdf[0]);")
    out.append("inline constexpr size_t kSingleCount   = sizeof(kSingle) / sizeof(kSingle[0]);")
    out.append("inline constexpr size_t kFragCount     = sizeof(kFrag) / sizeof(kFrag[0]);")
    out.append("inline constexpr size_t kNegativeCount = sizeof(kNegative) / sizeof(kNegative[0]);")
    out.append("")
    out.append("}  // namespace lran_vectors")
    out.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out))
    total = sum(len(g["vectors"]) for g in groups.values())
    print(f"wrote {OUT.relative_to(HERE.parent.parent)}: {total} vectors, "
          f"{OUT.stat().st_size // 1024} KB")
    return 0


if __name__ == "__main__":
    sys.exit(main())
